name: ovavue
description: A tidy budget overview planner.
publish_to: 'none'
version: 0.4.1+1

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  clock: ^1.1.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.0
  drift: ^2.13.1
  equatable: ^2.0.5
  faker: ^2.1.0
  file_picker: ^6.1.1
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.0.1
  flutter_sticky_header: ^0.6.5
  intl: ^0.19.0
  logging: ^1.2.0
  meta: ^1.11.0
  money:
    git: https://github.com/jogboms/money.dart.git
  package_info_plus: ^4.2.0
  path: ^1.8.3
  path_provider: ^2.1.1
  platform: ^3.1.3
  registry:
    git: https://github.com/jogboms/registry.dart.git
  riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1
  rxdart: ^0.27.7
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  sliver_tools: ^0.2.12
  sqlite3_flutter_libs: ^0.5.18
  tabler_icons: ^2.5.0+1
  universal_io: ^2.2.2
  url_launcher: ^6.2.1
  uuid: ^4.2.1

dependency_overrides:
  meta: 1.11.0 # required by analyzer

dev_dependencies:
  args:
  build_runner: ^2.4.6
  device_info_plus_platform_interface: ^7.0.0
  dotenv:
  drift_dev: ^2.13.2
  fake_async: ^1.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mfsao: ^3.0.0
  mocktail: ^1.0.1
  package_info_plus_platform_interface: ^2.0.1
  plugin_platform_interface: ^2.1.7
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.3.4
  test: ^1.24.9

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/ic_launcher_android.png"
  image_path_ios: "assets/ic_launcher_ios.png"
  min_sdk_android: 21
  remove_alpha_ios: true
