name: ovavue
description: A tidy budget overview planner.
publish_to: 'none'
version: 0.5.2+2

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.6"

dependencies:
  clock: ^1.1.2
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.2.0
  drift: ^2.29.0
  equatable: ^2.0.7
  faker: ^2.2.0
  file_picker: ^10.3.3
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^9.2.4
  flutter_slidable: ^4.0.3
  flutter_sticky_header: ^0.8.0
  intl: ^0.20.2
  logging: ^1.3.0
  meta: ^1.17.0
  money:
    git: https://github.com/jogboms/money.dart.git
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  platform: ^3.1.6
  registry:
    git: https://github.com/jogboms/registry.dart.git
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  rxdart: ">=0.27.0 <0.29.0"
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  sliver_tools: ^0.2.12
  sqlite3_flutter_libs: ^0.5.40
  tabler_icons: ^2.5.0+1
  universal_io: ^2.2.2
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  web: ^1.1.1

dependency_overrides:
  test_api: ^0.7.7

dev_dependencies:
  args:
  build_runner: ^2.10.1
  custom_lint:
  device_info_plus_platform_interface: ^7.0.3
  drift_dev: ^2.29.0
  fake_async: ^1.3.3
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  package_info_plus_platform_interface: ^3.2.1
  plugin_platform_interface: ^2.1.8
  riverpod_generator:
  riverpod_lint:
  test:

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/ic_launcher_android.png"
  image_path_ios: "assets/ic_launcher_ios.png"
  min_sdk_android: 21
  remove_alpha_ios: true
